spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-52-201-124-168.compute-1.amazonaws.com/dfb1er4v1qd15o
  username: tbfgcrbtiucane
  password: 375e9b90e963d16287e248481bb19b5fcf825a7319dda32f44528fddbf76b8f4
  platform: postgres
  driver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true

